version: 0.7.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    git submodule update --init --recursive

    cd Source
    
    start /wait Myra-Dependencies\MonoGameSetup.exe /S /v/qn

    msbuild Myra.sln /p:Configuration=Release /t:rebuild

    msbuild Myra.FNA.sln /p:Configuration=Release /t:rebuild

    nuget pack Myra\Myra.nuspec -Version %APPVEYOR_BUILD_VERSION%
    
    nuget pack Myra\Myra.FNA.nuspec -Version %APPVEYOR_BUILD_VERSION%

    nuget pack Myra.Editor\Myra.Editor.nuspec -Version %APPVEYOR_BUILD_VERSION%
    
    nuget pack Myra.Editor\Myra.Editor.FNA.nuspec -Version %APPVEYOR_BUILD_VERSION%

    copy_zip_package_files.bat
    
    rename "ZipPackage" "Myra.%APPVEYOR_BUILD_VERSION%"
    
    7z a Myra.%APPVEYOR_BUILD_VERSION%.zip Myra.%APPVEYOR_BUILD_VERSION%
artifacts:
  - path: Source/Myra.$(appveyor_build_version).nupkg
    name: Myra.nupkg

  - path: Source/Myra.FNA.$(appveyor_build_version).nupkg
    name: Myra.FNA.nupkg

  - path: Source/Myra.Editor.$(appveyor_build_version).nupkg
    name: Myra.Editor.nupkg

  - path: Source/Myra.Editor.FNA.$(appveyor_build_version).nupkg
    name: Myra.Editor.FNA.nupkg

  - path: Source/Myra.$(appveyor_build_version).zip
    name: ZipPackage
deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    description: $(appveyor_build_version)
    auth_token:
      secure: nIpZ5N6iQIXVV8/kK/Y6BqY4KYD+y7HYdq+vTKv+LqZBbxHE9BuEgZAHGVDvmJKh
    artifact: ZipPackage,MsiPackage
    draft: false
    prerelease: false

  - provider: NuGet
    api_key:
      secure: o02Abc+1Pg/C7FVPnbCA9i4RIakmOUcKjMBBCHDCbEhS69b+N05mV0xBe0ne2/Y4
    artifact: /.*\.nupkg/